server:
    port: 8888
databases:
    postgresql:
        host: localhost
        port: 5432
        database: db_main
        username: user_local
        password: auUmc2FutKX5frJad3uVpNM5mnbXhzS53AygPwijprD9qfabKYebggJpJKcWCN9NmQpUf7QM7wFcyg7AWMLhFTdHXy34fX7zvrMjbe9usMnPpAWS9KF779XTEAEQE22s
    sql-server:
        host: localhost
        port: 5432
        database: master
        username: sa
        password: P@ssw0rd
    max-pool: 17
    